### ISSUE TITLE
"juliomotol/laravel-auth-timeout": "^4.0", is not working with Laravel 10

### ISSUE THREAD

**Issue by abacusintlere** [juliomotol/laravel-channel-attributes#4]
I have installed package and added its alias into kernal.php and put into the web.php and try to login it forcefully logout and redirecting back to login page even I changed the timeout to 15 mins but it is not permitting to logged into system, kindly guide me where is the issue.

**Comment by juliomotol** [comment]
Hi, please reopen this issue in the appropriate repository. https://github.com/juliomotol/laravel-auth-timeout/issues

**Comment by abacusintlere** [comment]
Hi, I cant open this issue in the appropriate repo and it is redirecting to your laravel-channel-attributes repo.

**Comment by juliomotol** [comment]
Fixed, it. You can try again now.
